version: 1

# run_id: g3-med-hard-waiter
# run_id: g3-med-waiter
# run_id: g3-med-hard-waiter-explorer
run_id: g3-med-hard-05-split-enemy-vector

bob:
  consistent: true

peps:
  consistent: true

grievous:
  consistent: true
