version: 1

formatters:
    simple:
        format: "%(asctime)s %(levelname)-8s %(message)s"
        datefmt: '%Y-%m-%d %H:%M:%S'

    complex:
        format: "%(asctime)s %(filename)-15s %(levelname)-8s %(message)s"
        datefmt: '%Y-%m-%d %H:%M:%S'


handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple

    file_main:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        backupCount: 5
        level: DEBUG
        formatter: complex
        filename : logs/main.log

    file_bob:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        backupCount: 5
        level: DEBUG
        formatter: simple
        filename : logs/bob.log

    file_peps:
        class: logging.handlers.TimedRotatingFileHandler
        when: midnight
        backupCount: 5
        level: DEBUG
        formatter: simple
        filename : logs/peps.log


loggers:

    __main__: 
        level: DEBUG
        handlers: [console,file_main]
        propagate: yes

    bob: 
        level: DEBUG
        handlers: [file_bob]
        propagate: yes

    peps: 
        level: DEBUG
        handlers: [file_peps]
        filename: logs/econ.log
        propagate: yes

    L1:
        level: DEBUG
        handlers: [file_main]
        propagate: yes